---
kind: pipeline
type: docker
name: default
clone:
  disable: true
steps:
- name: clone
  image: alpine/git
  commands:
    - git clone https://gitclone.com/github.com/hash-roar/opeplatform.git
    - ls
    - mv opeplatform/*  ./  -f
    - ls

- name: deploy-prod
  image: docker/compose:1.29.2
  commands:
    - docker-compose up -d --remove-orphans
  depends_on:
    - clone
  when:
    branch:
      - master
    event:
      - push
  volumes:
    - name: sock
      path: /var/run/docker.sock

volumes:
  - name: sock
    host:
      path: /var/run/docker.sock
